# Setup
title:               How to make git blog
tagline:             'with Lanyon theme'
description:         '20223066@kookmin.ac.kr'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Hyewon Kim
  url:               https://twitter.com/mdo
  email:             20223066@koookmin.ac.kr

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
